WebShopApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebShopApp.Core.Contracts;
using WebShopApp.Core.Services;
using WebShopApp.Infrastructure.Data;
using WebShopApp.Infrastructure.Data.Entities;


namespace WebShopApp.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;


        public CartController(ICartService cartService, UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _cartService = cartService;
            _userManager = userManager;
            _context = context;
        }

        private string GetUserId() => _userManager.GetUserId(User);

        // GET: CartController
        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();
            var cart = await _cartService.GetCartByUserIdAsync(userId);
            ViewBag.Total = _cartService.CalculateTotalWithPromo(cart);
            return View(cart);
        }

        public async Task<IActionResult> Add(int productId)
        {
            var userId = GetUserId();
            await _cartService.AddItemAsync(userId, productId);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Remove(int productId)
        {
            var userId = GetUserId();
            await _cartService.RemoveItemAsync(userId, productId);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> IncreaseQuantity(int productId)
        {
            var userId = GetUserId();
            var cart = await _cartService.GetCartByUserIdAsync(userId);
            var item = cart.Items.FirstOrDefault(i => i.ProductId == productId);
            if (item != null)
            {
                await _cartService.UpdateQuantityAsync(userId, productId, item.Quantity + 1);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DecreaseQuantity(int productId)
        {
            var userId = GetUserId();
            var cart = await _cartService.GetCartByUserIdAsync(userId);
            var item = cart.Items.FirstOrDefault(i => i.ProductId == productId);
            if (item != null)
            {
                await _cartService.UpdateQuantityAsync(userId, productId, item.Quantity - 1);
            }
            if (item.Quantity <= 0)
            {
                cart.Items.Remove(item);
            }
            return RedirectToAction("Index");
        }




        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ApplyPromoCode(string code)
        {
            var userId = _userManager.GetUserId(User);
            var cart = await _cartService.GetCartByUserIdAsync(userId);

            if (string.IsNullOrWhiteSpace(code))
            {
                cart.AppliedPromoDiscountPercent = 0m;
                await _context.SaveChangesAsync();
                TempData["PromoError"] = "Невалиден промо код.";
                return RedirectToAction("Index");
            }

            var promo = await _context.PromoCodes
                .FirstOrDefaultAsync(p => p.Code == code && p.IsActive);

            if (promo == null)
            {
                cart.AppliedPromoDiscountPercent = 0m;
                await _context.SaveChangesAsync();
                TempData["PromoError"] = "Невалиден или изтекъл промо код.";
                return RedirectToAction("Index");
            }


            cart.AppliedPromoDiscountPercent = promo.DiscountPercent;
            await _context.SaveChangesAsync();

            TempData["PromoMessage"] = $"Промо кодът е приложен (-{promo.DiscountPercent}%)";

            return RedirectToAction("Index");
        }







        // GET: CartController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CartController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CartController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CartController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CartController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CartController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CartController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShopApp/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebShopApp.Core.Contracts;

using WebShopApp.Infrastructure.Data;
using WebShopApp.Infrastructure.Data.Entities;


namespace WebShopApp.Controllers
{
    public class FavoritesController : Controller
    {

        private readonly IFavoriteService _favoriteService;
        private readonly UserManager<ApplicationUser> _userManager;

        public FavoritesController(IFavoriteService favoriteService, UserManager<ApplicationUser> userManager)
        {
            _favoriteService = favoriteService;
            _userManager = userManager;
        }

        private string GetUserId() => _userManager.GetUserId(User);

        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();
            var products = await _favoriteService.GetFavoritesAsync(userId);
            return View(products);
        }


        public async Task<IActionResult> Add(int productId)
        {
            var userId = GetUserId();
            await _favoriteService.AddFavoriteAsync(userId, productId);
            return RedirectToAction("Index", "Product");
        }

        [Authorize]
        public async Task<IActionResult> Remove(int productId)
        {
            var userId = GetUserId();
            await _favoriteService.RemoveFavoriteAsync(userId, productId);
            return RedirectToAction("Index");
        }





        // GET: FavoritesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FavoritesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FavoritesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FavoritesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FavoritesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FavoritesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FavoritesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShopApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis;
using Microsoft.EntityFrameworkCore;
using WebShopApp.Core.Contracts;
using WebShopApp.Infrastructure.Data;
using WebShopApp.Infrastructure.Data.Entities;
using WebShopApp.Models.Brand;
using WebShopApp.Models.Product;

namespace WebShopApp.Controllers

{
    [Authorize(Roles = "Administrator")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IBrandService _brandService;
        private readonly ApplicationDbContext _context;


        public ProductController(IProductService productService, ICategoryService categoryService,
            IBrandService brandService, ApplicationDbContext context)
        {
            this._productService = productService;
            this._categoryService = categoryService;
            this._brandService = brandService;
            this._context = context;
        }


        // GET: ProductController
        [AllowAnonymous]
        public ActionResult Index(string searchStringCategoryName, string searchStringBrandName, string sort)
        {
            List<ProductIndexVM> products = _productService.GetProducts(searchStringCategoryName, searchStringBrandName)
                 .Select(product => new ProductIndexVM
                 {
                     Id = product.Id,
                     ProductName = product.ProductName,
                     BrandId = product.BrandId,
                     BrandName = product.Brand.BrandName,
                     CategoryId = product.CategoryId,
                     CategoryName = product.Category.CategoryName,
                     Picture = product.Picture,
                     Quantity = product.Quantity,
                     Price = product.Price,
                     Discount = product.Discount


                 }).ToList();

            switch (sort)
            {
                case "name_asc":
                    products = products.OrderBy(p => p.ProductName).ToList();
                    break;

                case "name_desc":
                    products = products.OrderByDescending(p => p.ProductName).ToList();
                    break;

                case "price_asc":
                    products = products.OrderBy(p => p.Price).ToList();
                    break;

                case "price_desc":
                    products = products.OrderByDescending(p => p.Price).ToList();
                    break;
            }


            return this.View(products);
        }

        // GET: ProductController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Product item = _productService.GetProductById(id);
            if (item == null)
            {
                return NotFound();
            }
            ProductDetailsVM product = new ProductDetailsVM()
            {
                Id = item.Id,
                ProductName = item.ProductName,
                BrandId = item.BrandId,
                BrandName = item.Brand.BrandName,
                CategoryId = item.CategoryId,
                CategoryName = item.Category.CategoryName,
                Picture = item.Picture,
                Quantity = item.Quantity,
                Price = item.Price,
                Discount = item.Discount
            };
            return this.View(product);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            var product = new ProductCreateVM();
            product.Brands = _brandService.GetBrands()
                .Select(x => new Models.Brand.BrandPairVM()
                {
                    Id = x.Id,
                    Name = x.BrandName
                }).ToList();
            product.Categories = _categoryService.GetCategories()
                .Select(x => new Models.Category.CategoryPairVM()
                {
                    Id = x.Id,
                    Name = x.CategoryName
                }).ToList();
            return View(product);


        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] ProductCreateVM product)
        {
            if (ModelState.IsValid)
            {
                var createdId = _productService.Create(product.ProductName, product.BrandId,
                    product.CategoryId, product.Picture, product.Quantity, product.Price, product.Discount);
                if (createdId)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            Product product = _productService.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }
            ProductEditVM updateProduct = new ProductEditVM()
            {
                Id = product.Id,
                ProductName = product.ProductName,
                BrandId = product.BrandId,
                //BrandName = product.Brand.BrandName,
                CategoryId = product.CategoryId,
                //CategoryName = product.Category.CategoryName,
                Picture = product.Picture,
                Quantity = product.Quantity,
                Price = product.Price,
                Discount = product.Discount
            };
            updateProduct.Brands = _brandService.GetBrands()
                .Select(b => new BrandPairVM()
                {
                    Id = b.Id,
                    Name = b.BrandName

                }).ToList();
            updateProduct.Categories = _categoryService.GetCategories()
                .Select(c => new Models.Category.CategoryPairVM()
                {
                    Id = c.Id,
                    Name = c.CategoryName
                }).ToList();
            return View(updateProduct);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ProductEditVM product)
        {
            if (ModelState.IsValid)
            {
                var updated = _productService.Update(id, product.ProductName,
                    product.BrandId, product.CategoryId, product.Picture,
                    product.Quantity, product.Price, product.Discount);
                if (updated)
                {
                    return this.RedirectToAction("Index");
                }
            }
            return View(product);
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            Product item = _productService.GetProductById(id);
            if (item == null)
            {
                return NotFound();
            }
            ProductDeleteVM product = new ProductDeleteVM()
            {
                Id = item.Id,
                ProductName = item.ProductName,
                BrandId = item.BrandId,
                BrandName = item.Brand.BrandName,
                CategoryId = item.CategoryId,
                CategoryName = item.Category.CategoryName,
                Picture = item.Picture,
                Quantity = item.Quantity,
                Price = item.Price,
                Discount = item.Discount


            };
            return View(product);



        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            var deleted = _productService.RemoveById(id);
            if (deleted)
            {
                return this.RedirectToAction("Success");
            }
            else
            {
                return View();
            }

        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

WebShopApp/Views/Product/Create.cshtml
@model WebShopApp.Models.Product.ProductCreateVM
@{
ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>ProductCreateVM</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                @*<input asp-for="BrandId" class="form-control" />*@
                <select asp-for="BrandId" class="form-control text-center">
                    @foreach (var brand in Model.Brands)
                    {
                    <option value=" @brand.Id">@brand.Name</option>
                    }
                </select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                @*<input asp-for="CategoryId" class="form-control" />*@
                <select asp-for="CategoryId" class="form-control text-center">
                    @foreach (var category in Model.Categories)
                    {
                    <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebShopApp/Views/Product/Delete.cshtml
@model WebShopApp.Models.Product.ProductDeleteVM
@{
    ViewData["Title"] = "Delete";
}
<h1>Delete</h1>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductDeleteVM</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Picture)" alt="Image"
                 width="100" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebShopApp/Views/Product/Details.cshtml
@model WebShopApp.Models.Product.ProductDetailsVM
@{
    ViewData["Title"] = "Details";
}
<h1>Details</h1>
<div>
    <h4>ProductDetailsVM</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Picture)" alt="Image"
                 width="100" />
            @*@Html.DisplayFor(model => model.Picture)*@
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>
</div>
<div>

    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebShopApp/Views/Product/Index.cshtml
@model IEnumerable<WebShopApp.Models.Product.ProductIndexVM>

    @{
    ViewData["Title"] = "Products";
    }

    <div class="container my-5">
        <h1 class="mb-4">Products</h1>

        @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
    {
        <a asp-action="Create" class="btn btn-primary mb-4">Create New</a>
    }

        <!-- FILTER -->

        <form asp-controller="Product" asp-action="Index" method="get" class="row g-3 mb-4 align-items-end">
            <div class="col-md-3">
                <input type="text" name="SearchStringBrandName"
                       class="form-control"
                       placeholder="Brand">
            </div>
            <div class="col-md-3">
                <input type="text" name="SearchStringCategoryName"
                       class="form-control"
                       placeholder="Category">
            </div>
            <div class="col-md-2">
                <select name="sort" class="form-select" onchange="this.form.submit()">
                    <option value="">Подреди...</option>
                    <option value="name_asc">A → Z</option>
                    <option value="name_desc">Z → A</option>
                    <option value="price_asc">Цена ↑</option>
                    <option value="price_desc">Цена ↓</option>
                </select>
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary w-100">
                    Filter
                </button>
            </div>
        </form>



        <!-- PRODUCTS GRID -->
        <div class="row g-4">
            @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                <!-- добавяме mb-4 -->
                <div class="card product-card h-100">
                    <img src="@item.Picture"
                         class="card-img-top product-image"
                         alt="@item.ProductName">

                    <div class="card-body d-flex flex-column">
                        <h6 class="card-title">@item.ProductName</h6>
                        <small class="text-muted">@item.BrandName • @item.CategoryName</small>
                        @* <p class="fw-bold mt-2">@item.Price лв.</p> *@

                        @if (item.Discount > 0)
                        {
                        <span class="badge bg-danger mb-2">-@item.Discount%</span>
                        }

                        <div class="mt-auto d-grid gap-2">
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success btn-sm">Details</a>

                            @if (User.Identity.IsAuthenticated)
                            {
                            <a asp-controller="Order" asp-action="Create" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Order</a>
                            }

                            @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                            {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning btn-sm">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm">Delete</a>
                            }
                        </div>

                        <p class="fw-bold mt-2">
                            @if (item.Discount > 0)
                            {
                            <span class="text-muted text-decoration-line-through">
                                @item.Price.ToString("0.00") лв.
                            </span>
                            <span class="text-danger">
                                @item.DiscountedPrice.ToString("0.00") лв.
                            </span>
                            }
                            else
                            {
                            <span>
                                @item.Price.ToString("0.00") лв.
                            </span>
                            }
                        </p>

                    </div>

                    <div class="card-footer d-flex justify-content-between">
                        <a asp-controller="Cart" asp-action="Add" asp-route-productId="@item.Id" class="btn btn-primary btn-sm">Add to cart</a>

                        @if (User.Identity.IsAuthenticated)
                        {
                        <a asp-controller="Favorites" asp-action="Add" asp-route-productId="@item.Id" class="btn btn-outline-danger btn-sm">❤️ Любими</a>
                        }
                    </div>
                </div>
            </div>

        }
        </div>


    </div>

WebShopApp/Views/Product/Success.cshtml
@{
    ViewData["Title"] = "Success";
}
<h1>You successfully removed a product!</h1>
<div>
    <a asp-action="Index">Back to list</a>
</div>